=== pacsayt/sghome/src/main/resources/QuickTip.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="abstractQuickTipAlgorithmARN">
    <xs:sequence>
      <xs:element name="amountRandomNumbers" type="xs:positiveInteger"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="quickTipAlgorithmULType">
    <xs:complexContent>
      <xs:extension base="abstractQuickTipAlgorithmARN">
        <xs:sequence>
          <xs:element name="upperLimit" type="xs:positiveInteger"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="quickTipAlgorithmAPType">
    <xs:complexContent>
      <xs:extension base="abstractQuickTipAlgorithmARN">
        <xs:sequence>
          <xs:element name="amountOfPanels" type="xs:positiveInteger"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

    <xs:complexType name="quickTipAlgorithmULAPType">
      <xs:complexContent>
        <xs:extension base="abstractQuickTipAlgorithmARN">
          <xs:sequence>
            <xs:element name="upperLimit" type="xs:positiveInteger"/>
            <xs:element name="amountOfPanels" type="xs:positiveInteger"/>
          </xs:sequence>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>

  <xs:element name="quickTips">
    <xs:complexType mixed="true">
      <xs:sequence>

        <xs:element name="quickTipAlgorithmUL" type="quickTipAlgorithmULType"/>

        <xs:element name="quickTipAlgorithmAP" type="quickTipAlgorithmAPType"/>

        <xs:element name="quickTipAlgorithmULAP" type="quickTipAlgorithmULAPType"/>

      </xs:sequence>
    </xs:complexType>
  </xs:element>


</xs:schema>

=== pacsayt/sghome/src/main/resources/QuickTip.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!-- https://stackoverflow.com/questions/34202967/xmlns-xmlnsxsi-xsischemalocation-and-targetnamespace/34204799 -->

<quickTips xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="QuickTip.xsd"> <!-- xsi:schemaLocation ??? -->
      <!-- xsi:schemaLocation="https://www.gshomework.com/xml QuickTip.xsd"> -->
  <quickTipAlgorithmUL>
    <amountRandomNumbers>5</amountRandomNumbers>
    <upperLimit>90</upperLimit>
  </quickTipAlgorithmUL>

  <quickTipAlgorithmAP>
    <amountRandomNumbers>5</amountRandomNumbers>
    <amountOfPanels>3</amountOfPanels>
  </quickTipAlgorithmAP>

  <quickTipAlgorithmULAP>
    <amountRandomNumbers>5</amountRandomNumbers>
    <upperLimit>90</upperLimit>
    <amountOfPanels>3</amountOfPanels>
  </quickTipAlgorithmULAP>>

</quickTips>
